### ISSUE TITLE
PayPal pro flow - CCGV issues

### ISSUE THREAD

**Issue by ampmgirl** [DynamoEffects/paypal-payflow-pro-for-oscommerce#1]
Hi Brian,

I hope this is the right place to post this.  I am sorry for the long delay but my ISP moved me from one pool to a different server pool and it created numerous errors with the shopping cart.  I have been working over the past week with them to correct the issues.

I have the report from Paypal and I want to make sure not to include the API.  Can you give me an example of what it might look like since I do not see anything that says API.  That way i can edit/delete it.

Thanks for you help.. It is always appreciated
Taylor

**Comment by DynamoEffects** [comment]
Hi Taylor,

The API is not something you can delete, it's simply the instruction set used when speaking between your server and PayPal's servers.  Think of it as deleting Mathematics while doing your math homework or deleting English while speaking to a friend -- it's not possible.

What exactly are you wanting to not include?  Your username and password?
