### ISSUE TITLE
Oscommerce Paypal-payflow pro

### ISSUE THREAD

**Issue by tvadivelu** [DynamoEffects/paypal-payflow-pro-for-oscommerce#2]
I have used your contribution for paypal payflow pro, i have paid the amount using credit card, once the payment is processed i have redirected to checkout success, but the Amount is not Transferred to Admin Account. could u please help me to sort out this issue.

i have get mail in Admin with the message
RESULT=1&RESPMSG=User authentication failed

**Comment by DynamoEffects** [comment]
Open your /includes/modules/payment/paypal_payflow_pro.php file find this line:

$result = strstr($result, "RESULT");

ABOVE that line, add this:

mail(STORE_OWNER_EMAIL_ADDRESS, 'Payflow Response', $result);

Then strip out any sensitive information like credit card numbers, usernames and passwords and then let me see what it says.

**Comment by tvadivelu** [comment]
in Admin mail i have received message like
RESULT=1&RESPMSG=User authentication failed

**Comment by tvadivelu** [comment]
could u please help me to sort out this issues

**Comment by DynamoEffects** [comment]
That means that your Payflow Pro username/password is incorrect.  Contact PayPal support for assistance in locating the correct username and password.

**Comment by tvadivelu** [comment]
Credentials: Vendor/Merchant
Credentials: User
Credentials: Password

Could u give me example above of this. to ask for correct username and password

**Comment by tvadivelu** [comment]
Could u provide example to ask for correct username and password
