### ISSUE TITLE
Oscommerce Paypal-payflow pro

### ISSUE THREAD

**Issue by tvadivelu** [DynamoEffects/paypal-payflow-pro-for-oscommerce#3]
DynamoEffects 42 minutes ago | link

Open your /includes/modules/payment/paypal_payflow_pro.php file find this line:

$result = strstr($result, "RESULT");

ABOVE that line, add this:

mail(STORE_OWNER_EMAIL_ADDRESS, 'Payflow Response', $result);

Then strip out any sensitive information like credit card numbers, usernames and passwords and then let me see what it says.
Comment
Open your /includes/modules/payment/paypal_payflow_pro.php file find this line: $result = strstr($result, "RESULT"); ABOVE that line, add this: mail(STORE_OWNER_EMAIL_ADDRESS, 'Payflow Response', $result); Then strip out any sensitive information like credit card numbers, usernames and passwords and then let me see what it says.
or cancel
tvadivelu 36 minutes ago | link | edit | delete

in Admin mail i have received message like
RESULT=1&RESPMSG=User authentication failed
Comment
in Admin mail i have received message like RESULT=1&RESPMSG=User authentication failed
or cancel
tvadivelu 36 minutes ago | link | edit | delete

could u please help me to sort out this issues
Comment
could u please help me to sort out this issues
or cancel
DynamoEffects 31 minutes ago | link

That means that your Payflow Pro username/password is incorrect. Contact PayPal support for assistance in locating the correct username and password.
Comment
That means that your Payflow Pro username/password is incorrect. Contact PayPal support for assistance in locating the correct username and password.
or cancel
tvadivelu 5 minutes ago | link | edit | delete

Credentials: Vendor/Merchant
Credentials: User
Credentials: Password

Could u give me example above of this. to ask for correct username and password
Comment
Credentials: Vendor/Merchant Credentials: User Credentials: Password Could u give me example above of this. to ask for correct username and password
or cancel
tvadivelu just now | link | edit | delete

Could u provide example to ask for correct username and password

**Comment by DynamoEffects** [comment]
Contact your Paypal account representative and as them for your Payflow Pro credentials.  They will tell you exactly what you need to know and they are the only ones who can tell you.  This is not something I can help you with as it is NOT a problem with the module itself.  Do not reopen this issue.
