### ISSUE TITLE
Tax Amount

### ISSUE THREAD

**Issue by robertal** [DynamoEffects/paypal-payflow-pro-for-oscommerce#4]
Hi,
  We're currently have your PayPal Payflow Pro for osCommerce 2.2MS2+ module installed, and have been testing it for use on a new store.  However, I'm noticing that the tax amount, although it submits to paypal under the tax field, does not also add to the total amount, and thus does not get charged to the customer.  Do you know why this is or how I can fix it?  Thanks very much for your time!

Best Regards,
Alex

**Comment by DynamoEffects** [comment]
If you have the "Display Prices with Tax" configuration option enabled in your store, that is one possibility.  Please confirm that it is set to False in Configuration -> My Store -> Display Prices with Tax

**Comment by robertal** [comment]
Hi,
  Thank you very much.  It looks like that was the issue.  My apologies for thinking it was the processing and not a simple setting like this.  I really appreciate it.

Best Regards,
Alex
