### ISSUE TITLE
Sorry for spam

### ISSUE THREAD

**Issue by jos1337** [DynamoEffects/paypal-payflow-pro-for-oscommerce#5]
@DynamoEffects 
Sorry for the spam, I'm new to github and not sure how to reach to you. I tried to post an issue on ur angular 2 signature pad fork, but it not possible. So I did try to contact you in the original repo but they closed it as spam. So this is the only way I know to reach you. Sorry
I would love to use you signature pad fork and it working fine on ng serve. But as soon as I try to build the app with or without aot it get an error:
ERROR in 1.6196aa3e0aba2b2f4b70.chunk.js from UglifyJs
Unexpected token: name (length) [1.6196aa3e0aba2b2f4b70.chunk.js:119364,7]
Do you have any idea what could be causing this?
Thank you very much

**Comment by DynamoEffects** [comment]
No idea, I build Ionic apps using build.phonegap.com and don't have any problems.  Try building there, it's free.  Another option would be to hire a dev (not me) from a freelancer site to debug the problem, you could probably get it done for $50.
